export { default as LandingNavbar } from "./LandingNavbar";
export { default as HeroSection } from "./HeroSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as ProcessSection } from "./ProcessSection";
export { default as PricingSection } from "./PricingSection";
export { default as InstallOnPhoneSection } from "./InstallOnPhoneSection";
export { default as TestimonialsSection } from "./TestimonialsSection";
export { default as CtaSection } from "./CtaSection";
export { default as LandingFooter } from "./LandingFooter";